// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Q5A6tynfAs_I06HBSWciKxBdG1NcKq4',
    appId: '1:797691888872:web:e7d6a0398f6e38b0c9f55d',
    messagingSenderId: '797691888872',
    projectId: 'learn-up-530c9',
    authDomain: 'learn-up-530c9.firebaseapp.com',
    storageBucket: 'learn-up-530c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe4X7FnfFUihMYVgshf2rNI1GeJK8FKd0',
    appId: '1:797691888872:android:0b078b66a1736639c9f55d',
    messagingSenderId: '797691888872',
    projectId: 'learn-up-530c9',
    storageBucket: 'learn-up-530c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCwSRyZP4KmWNDsGC9xYo2ss7ExCDFBCs',
    appId: '1:797691888872:ios:49f885cc6383a4a4c9f55d',
    messagingSenderId: '797691888872',
    projectId: 'learn-up-530c9',
    storageBucket: 'learn-up-530c9.appspot.com',
    iosBundleId: 'com.example.learnup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCwSRyZP4KmWNDsGC9xYo2ss7ExCDFBCs',
    appId: '1:797691888872:ios:49f885cc6383a4a4c9f55d',
    messagingSenderId: '797691888872',
    projectId: 'learn-up-530c9',
    storageBucket: 'learn-up-530c9.appspot.com',
    iosBundleId: 'com.example.learnup',
  );
}
